"""make url nullable

Revision ID: 135e1ae46fb
Revises: 5a0620f00bb
Create Date: 2015-01-24 11:36:12.764173

"""

# revision identifiers, used by Alembic.
revision = '135e1ae46fb'
down_revision = '5a0620f00bb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pages', 'url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pages', 'url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    ### end Alembic commands ###
