"""Add size_values table

Revision ID: 196d540b240
Revises: 33c569fc15e
Create Date: 2015-01-04 19:35:54.972375

"""

# revision identifiers, used by Alembic.
revision = '196d540b240'
down_revision = '33c569fc15e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('size_values',
    sa.Column('version', sa.DateTime(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=120), nullable=True),
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('size_id', sa.String(length=255), nullable=False),
    sa.Column('shoulders', sa.String(length=20), nullable=False),
    sa.Column('chest', sa.String(length=20), nullable=False),
    sa.Column('waist', sa.String(length=20), nullable=False),
    sa.Column('hips', sa.String(length=20), nullable=False),
    sa.Column('inside_leg', sa.String(length=20), nullable=False),
    sa.Column('external_leg', sa.String(length=20), nullable=False),
    sa.Column('coat_length', sa.String(length=20), nullable=False),
    sa.Column('sleeve', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['size_id'], ['sizes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sizes', sa.Column('size_type', sa.String(length=10), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sizes', 'size_type')
    op.drop_table('size_values')
    ### end Alembic commands ###
