"""populate sizes

Revision ID: 1ea035e8c61
Revises: 196d540b240
Create Date: 2015-01-04 22:09:56.347817

"""

# revision identifiers, used by Alembic.
from suittale.core import generate_uuid

revision = '1ea035e8c61'
down_revision = '196d540b240'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.sql import table
from datetime import datetime


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suit_size_guides',
                    sa.Column('version', sa.DateTime(), nullable=True),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.String(length=120), nullable=True),
                    sa.Column('id', sa.String(length=255), nullable=False),
                    sa.Column('type', sa.String(length=40), nullable=False),
                    sa.Column('size', sa.String(length=5), nullable=False),
                    sa.Column('shoulders', sa.String(length=20), nullable=False),
                    sa.Column('chest', sa.String(length=20), nullable=False),
                    sa.Column('waist', sa.String(length=20), nullable=False),
                    sa.Column('hips', sa.String(length=20), nullable=False),
                    sa.Column('inside_leg', sa.String(length=20), nullable=False),
                    sa.Column('external_leg', sa.String(length=20), nullable=False),
                    sa.Column('coat_length', sa.String(length=20), nullable=False),
                    sa.Column('sleeve', sa.String(length=20), nullable=False),
                    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('size_values')
    # Data operations
    sizes = table('sizes',
                  sa.Column('version', sa.DateTime, onupdate=datetime.utcnow),
                  sa.Column('creation_date', sa.DateTime, default=datetime.utcnow),
                  sa.Column('updated_by', sa.String(120), nullable=True),
                  sa.Column('id', sa.String(255), primary_key=True, default=generate_uuid),
                  sa.Column('size', sa.String(5), nullable=False),
                  sa.Column('size_type', sa.String(10), nullable=False))

    op.bulk_insert(sizes,
                   [
                       {'size': '42', 'size_type': 'MAN'},
                       {'size': '44', 'size_type': 'MAN'},
                       {'size': '46', 'size_type': 'MAN'},
                       {'size': '48', 'size_type': 'MAN'},
                       {'size': '50', 'size_type': 'MAN'},
                       {'size': '52', 'size_type': 'MAN'},
                       {'size': '54', 'size_type': 'MAN'},
                       {'size': '56', 'size_type': 'MAN'},
                       {'size': '58', 'size_type': 'MAN'},
                       {'size': '60', 'size_type': 'MAN'},
                   ])

    suit_size_guides = table('suit_size_guides', sa.Column('version', sa.DateTime, onupdate=datetime.utcnow),
                             sa.Column('creation_date', sa.DateTime, default=datetime.utcnow),
                             sa.Column('updated_by', sa.String(120), nullable=True),
                             sa.Column('id', sa.String(255), primary_key=True, default=generate_uuid),
                             sa.Column('size', sa.String(5), nullable=False),
                             sa.Column('type', sa.String(40), nullable=False),
                             sa.Column('shoulders', sa.String(20), nullable=False),
                             sa.Column('chest', sa.String(20), nullable=False),
                             sa.Column('waist', sa.String(20), nullable=False),
                             sa.Column('hips', sa.String(20), nullable=False),
                             sa.Column('inside_leg', sa.String(20), nullable=False),
                             sa.Column('external_leg', sa.String(20), nullable=False),
                             sa.Column('coat_length', sa.String(20), nullable=False),
                             sa.Column('sleeve', sa.String(20), nullable=False))

    op.bulk_insert(suit_size_guides,
                   [
                       {'type': 'T1',
                        'size': '42', 'shoulders': '42-43',
                        'chest': '96-97',
                        'waist': '75-78',
                        'hips': '92-94',
                        'inside_leg': '88',
                        'external_leg': '109',
                        'coat_length': '76',
                        'sleeve': '63'},
                       {'type': 'T1',
                        'size': '44', 'shoulders': '44',
                        'chest': '98-99',
                        'waist': '79-82',
                        'hips': '95-97',
                        'inside_leg': '88',
                        'external_leg': '110',
                        'coat_length': '76,5',
                        'sleeve': '63,5'},
                       {'type': 'T1',
                        'size': '46', 'shoulders': '45',
                        'chest': '100-101',
                        'waist': '83-86',
                        'hips': '98-100',
                        'inside_leg': '88',
                        'external_leg': '111',
                        'coat_length': '77',
                        'sleeve': '64'},
                       {'type': 'T1',
                        'size': '48', 'shoulders': '46',
                        'chest': '102-103',
                        'waist': '87-90',
                        'hips': '101-103',
                        'inside_leg': '89',
                        'external_leg': '111',
                        'coat_length': '77,5',
                        'sleeve': '64,5'},
                       {'type': 'T1',
                        'size': '50', 'shoulders': '47-48',
                        'chest': '104-105',
                        'waist': '91-94',
                        'hips': '104-106',
                        'inside_leg': '89',
                        'external_leg': '111',
                        'coat_length': '78',
                        'sleeve': '65'},
                       {'type': 'T1',
                        'size': '52', 'shoulders': '49',
                        'chest': '106-107',
                        'waist': '95-98',
                        'hips': '107-109',
                        'inside_leg': '90',
                        'external_leg': '112',
                        'coat_length': '78,5',
                        'sleeve': '65,5'},
                       {'type': 'T1',
                        'size': '54', 'shoulders': '50',
                        'chest': '108-109',
                        'waist': '99-102',
                        'hips': '110-112',
                        'inside_leg': '90',
                        'external_leg': '112',
                        'coat_length': '79',
                        'sleeve': '66'},
                       {'type': 'T1',
                        'size': '56', 'shoulders': '51-52',
                        'chest': '110-111',
                        'waist': '103-106',
                        'hips': '113-115',
                        'inside_leg': '90',
                        'external_leg': '112',
                        'coat_length': '79,5',
                        'sleeve': '66,5'},
                       {'type': 'T1',
                        'size': '58', 'shoulders': '53',
                        'chest': '112-113',
                        'waist': '107-110',
                        'hips': '116-118',
                        'inside_leg': '91',
                        'external_leg': '113',
                        'coat_length': '80',
                        'sleeve': '67'},
                       {'type': 'T1',
                        'size': '60', 'shoulders': '54',
                        'chest': '114-115',
                        'waist': '111-114',
                        'hips': '119-121',
                        'inside_leg': '91',
                        'external_leg': '113',
                        'coat_length': '80,5',
                        'sleeve': '67,5'}
                   ])

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('size_values',
                    sa.Column('version', mysql.DATETIME(), nullable=True),
                    sa.Column('creation_date', mysql.DATETIME(), nullable=True),
                    sa.Column('updated_by', mysql.VARCHAR(length=120), nullable=True),
                    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
                    sa.Column('size_id', mysql.VARCHAR(length=255), nullable=False),
                    sa.Column('shoulders', mysql.VARCHAR(length=20), nullable=False),
                    sa.Column('chest', mysql.VARCHAR(length=20), nullable=False),
                    sa.Column('waist', mysql.VARCHAR(length=20), nullable=False),
                    sa.Column('hips', mysql.VARCHAR(length=20), nullable=False),
                    sa.Column('inside_leg', mysql.VARCHAR(length=20), nullable=False),
                    sa.Column('external_leg', mysql.VARCHAR(length=20), nullable=False),
                    sa.Column('coat_length', mysql.VARCHAR(length=20), nullable=False),
                    sa.Column('sleeve', mysql.VARCHAR(length=20), nullable=False),
                    sa.ForeignKeyConstraint(['size_id'], ['sizes.id'], name='size_values_ibfk_1'),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_default_charset='utf8',
                    mysql_engine='InnoDB'
    )
    op.drop_table('suit_size_guides')
    ### end Alembic commands ###
