"""add children pages

Revision ID: 2729b656599
Revises: 34d67b2c4a6
Create Date: 2015-01-21 20:20:05.444864

"""

# revision identifiers, used by Alembic.
revision = '2729b656599'
down_revision = '34d67b2c4a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('parent_id', sa.String(length=255), nullable=True))
    op.add_column('pages', sa.Column('second_content', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'pages', 'pages', ['parent_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pages', type_='foreignkey')
    op.drop_column('pages', 'second_content')
    op.drop_column('pages', 'parent_id')
    ### end Alembic commands ###
