"""add titles

Revision ID: 30108daf60
Revises: 294b57e0c28
Create Date: 2015-01-24 23:37:35.572666

"""

# revision identifiers, used by Alembic.
revision = '30108daf60'
down_revision = '294b57e0c28'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('content_title', sa.String(length=100), nullable=True))
    op.add_column('pages', sa.Column('second_content_title', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'second_content_title')
    op.drop_column('pages', 'content_title')
    ### end Alembic commands ###
