"""product matrix table

Revision ID: 335d53bb657
Revises: 1ea035e8c61
Create Date: 2015-01-10 19:36:39.363673

"""

# revision identifiers, used by Alembic.
revision = '335d53bb657'
down_revision = '1ea035e8c61'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_matrix',
    sa.Column('version', sa.DateTime(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=120), nullable=True),
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.String(length=255), nullable=False),
    sa.Column('size_id', sa.String(length=255), nullable=False),
    sa.Column('texture_id', sa.String(length=255), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['size_id'], ['sizes.id'], ),
    sa.ForeignKeyConstraint(['texture_id'], ['textures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'size_id', 'texture_id', name='_product_matrix_uc')
    )
    op.drop_table('product_sizes')
    op.create_unique_constraint('_product_attribute_uc', 'product_attributes', ['product_id', 'attribute_id'])
    op.add_column('products', sa.Column('available', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description')
    op.drop_column('products', 'available')
    op.drop_constraint('_product_attribute_uc', 'product_attributes', type_='unique')
    op.create_table('product_sizes',
    sa.Column('size_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('product_id', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_sizes_ibfk_1'),
    sa.ForeignKeyConstraint(['size_id'], ['sizes.id'], name='product_sizes_ibfk_2'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('products_matrix')
    ### end Alembic commands ###
