"""initial migration

Revision ID: 33c569fc15e
Revises: None
Create Date: 2015-01-04 17:48:11.277779

"""

# revision identifiers, used by Alembic.
from datetime import datetime
from suittale.core import generate_uuid

revision = '33c569fc15e'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
                    sa.Column('version', sa.DateTime(), nullable=True),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.String(length=120), nullable=True),
                    sa.Column('id', sa.String(length=255), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('template', sa.Text(), nullable=True),
                    sa.Column('parent_id', sa.String(length=255), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
    )
    op.create_table('countries',
                    sa.Column('version', sa.DateTime(), nullable=True),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.String(length=120), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('code', sa.String(length=3), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('code'),
                    sa.UniqueConstraint('name')
    )
    op.create_table('textures',
                    sa.Column('version', sa.DateTime(), nullable=True),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.String(length=120), nullable=True),
                    sa.Column('id', sa.String(length=255), nullable=False),
                    sa.Column('code', sa.String(length=50), nullable=False),
                    sa.Column('composition', sa.String(length=100), nullable=True),
                    sa.Column('image', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('code')
    )
    op.create_table('sizes',
                    sa.Column('version', sa.DateTime(), nullable=True),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.String(length=120), nullable=True),
                    sa.Column('id', sa.String(length=255), nullable=False),
                    sa.Column('size', sa.String(length=5), nullable=False),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attributes',
                    sa.Column('version', sa.DateTime(), nullable=True),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.String(length=120), nullable=True),
                    sa.Column('id', sa.String(length=255), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('code', sa.String(length=100), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
                    sa.Column('version', sa.DateTime(), nullable=True),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.String(length=120), nullable=True),
                    sa.Column('id', sa.String(length=255), nullable=False),
                    sa.Column('name', sa.String(length=80), nullable=True),
                    sa.Column('description', sa.String(length=200), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
    )
    op.create_table('regions',
                    sa.Column('version', sa.DateTime(), nullable=True),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.String(length=120), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('code', sa.String(length=3), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('country_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
                    sa.Column('version', sa.DateTime(), nullable=True),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.String(length=120), nullable=True),
                    sa.Column('id', sa.String(length=255), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('code', sa.String(length=100), nullable=False),
                    sa.Column('short_description', sa.String(length=255), nullable=True),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('currency', sa.String(length=3), nullable=False),
                    sa.Column('texture_id', sa.String(length=255), nullable=False),
                    sa.ForeignKeyConstraint(['texture_id'], ['textures.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('code')
    )
    op.create_table('product_sizes',
                    sa.Column('size_id', sa.String(length=255), nullable=True),
                    sa.Column('product_id', sa.String(length=255), nullable=True),
                    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
                    sa.ForeignKeyConstraint(['size_id'], ['sizes.id'], )
    )
    op.create_table('product_attributes',
                    sa.Column('version', sa.DateTime(), nullable=True),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.String(length=120), nullable=True),
                    sa.Column('id', sa.String(length=255), nullable=False),
                    sa.Column('value', sa.String(length=255), nullable=False),
                    sa.Column('attribute_id', sa.String(length=255), nullable=False),
                    sa.Column('product_id', sa.String(length=255), nullable=False),
                    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ),
                    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('product_id', 'attribute_id', name='_product_measure_uc')
    )
    op.create_table('product_categories',
                    sa.Column('category_id', sa.String(length=255), nullable=True),
                    sa.Column('product_id', sa.String(length=255), nullable=True),
                    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
                    sa.ForeignKeyConstraint(['product_id'], ['products.id'], )
    )
    op.create_table('product_images',
                    sa.Column('version', sa.DateTime(), nullable=True),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.String(length=120), nullable=True),
                    sa.Column('id', sa.String(length=255), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('image', sa.String(length=255), nullable=False),
                    sa.Column('default', sa.Boolean(), nullable=False),
                    sa.Column('product_id', sa.String(length=255), nullable=False),
                    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cities',
                    sa.Column('version', sa.DateTime(), nullable=True),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.String(length=120), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('region_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
                    sa.Column('version', sa.DateTime(), nullable=True),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.String(length=120), nullable=True),
                    sa.Column('id', sa.String(length=255), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('type', sa.String(length=2), nullable=False),
                    sa.Column('unique_id', sa.String(length=30), nullable=False),
                    sa.Column('phone', sa.String(length=14), nullable=False),
                    sa.Column('address', sa.String(length=255), nullable=False),
                    sa.Column('iban', sa.String(length=50), nullable=True),
                    sa.Column('bank', sa.String(length=100), nullable=True),
                    sa.Column('swift', sa.String(length=20), nullable=True),
                    sa.Column('city_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('unique_id')
    )
    op.create_table('users',
                    sa.Column('version', sa.DateTime(), nullable=True),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.String(length=120), nullable=True),
                    sa.Column('id', sa.String(length=255), nullable=False),
                    sa.Column('first_name', sa.String(length=50), nullable=False),
                    sa.Column('last_name', sa.String(length=50), nullable=False),
                    sa.Column('phone', sa.String(length=14), nullable=False),
                    sa.Column('birth_date', sa.Date(), nullable=False),
                    sa.Column('email', sa.String(length=50), nullable=False),
                    sa.Column('password', sa.String(length=20), nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('admin', sa.Boolean(), nullable=True),
                    sa.Column('last_login_at', sa.DateTime(), nullable=True),
                    sa.Column('current_login_at', sa.DateTime(), nullable=True),
                    sa.Column('last_login_ip', sa.String(length=16), nullable=True),
                    sa.Column('current_login_ip', sa.String(length=16), nullable=True),
                    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
                    sa.Column('login_count', sa.Integer(), nullable=True),
                    sa.Column('customer_id', sa.String(length=255), nullable=True),
                    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
    )
    op.create_table('addresses',
                    sa.Column('version', sa.DateTime(), nullable=True),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.String(length=120), nullable=True),
                    sa.Column('id', sa.String(length=255), nullable=False),
                    sa.Column('contact_person', sa.String(length=255), nullable=False),
                    sa.Column('phone', sa.String(length=14), nullable=False),
                    sa.Column('address', sa.String(length=255), nullable=False),
                    sa.Column('is_default', sa.Boolean(), nullable=False),
                    sa.Column('customer_id', sa.String(length=255), nullable=True),
                    sa.Column('city_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
                    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_users',
                    sa.Column('user_id', sa.String(length=255), nullable=True),
                    sa.Column('role_id', sa.String(length=255), nullable=True),
                    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    ### Create ROLES ###
    roles_table = table('roles',
                        sa.Column('version', sa.DateTime, onupdate=datetime.utcnow),
                        sa.Column('creation_date', sa.DateTime, default=datetime.utcnow),
                        sa.Column('updated_by', sa.String(120), nullable=True),
                        sa.Column('id', sa.String(255), primary_key=True, default=generate_uuid),
                        sa.Column('name', sa.String(80), unique=True),
                        sa.Column('description', sa.String(200))
    )

    op.bulk_insert(roles_table,
    [
        {'name': 'ADMINISTRATOR'},
        {'name': 'ACCOUNT_MANAGER'},
        {'name': 'CUSTOMER'},
    ]
)

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    op.drop_table('addresses')
    op.drop_table('users')
    op.drop_table('customers')
    op.drop_table('cities')
    op.drop_table('product_images')
    op.drop_table('product_categories')
    op.drop_table('product_attributes')
    op.drop_table('product_sizes')
    op.drop_table('products')
    op.drop_table('regions')
    op.drop_table('roles')
    op.drop_table('attributes')
    op.drop_table('sizes')
    op.drop_table('textures')
    op.drop_table('countries')
    op.drop_table('categories')
    ### end Alembic commands ###
