"""add site tables

Revision ID: 34d67b2c4a6
Revises: 335d53bb657
Create Date: 2015-01-20 13:01:05.947356

"""

# revision identifiers, used by Alembic.
revision = '34d67b2c4a6'
down_revision = '335d53bb657'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pages',
    sa.Column('version', sa.DateTime(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=120), nullable=True),
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('keywords', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carousel_images',
    sa.Column('version', sa.DateTime(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=120), nullable=True),
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('page_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carousel_images')
    op.drop_table('pages')
    ### end Alembic commands ###
