"""initial migration

Revision ID: 34ef0993e28
Revises: None
Create Date: 2015-01-01 22:19:04.423822

"""

# revision identifiers, used by Alembic.
revision = '34ef0993e28'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_textures',
    sa.Column('texture_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('product_id', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_textures_ibfk_2'),
    sa.ForeignKeyConstraint(['texture_id'], ['textures.id'], name='product_textures_ibfk_1'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('addresses',
    sa.Column('version', mysql.DATETIME(), nullable=True),
    sa.Column('creation_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('contact_person', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=14), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('is_default', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('customer_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('city_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name='addresses_ibfk_2'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='addresses_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('products',
    sa.Column('version', mysql.DATETIME(), nullable=True),
    sa.Column('creation_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('short_description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.Column('currency', mysql.VARCHAR(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('cities',
    sa.Column('version', mysql.DATETIME(), nullable=True),
    sa.Column('creation_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('region_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name='cities_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('product_images',
    sa.Column('version', mysql.DATETIME(), nullable=True),
    sa.Column('creation_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('image', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('default', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('product_id', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_images_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('roles',
    sa.Column('version', mysql.DATETIME(), nullable=True),
    sa.Column('creation_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('version', mysql.DATETIME(), nullable=True),
    sa.Column('creation_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=14), nullable=False),
    sa.Column('birth_date', sa.DATE(), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('last_login_at', mysql.DATETIME(), nullable=True),
    sa.Column('current_login_at', mysql.DATETIME(), nullable=True),
    sa.Column('last_login_ip', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('current_login_ip', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('confirmed_at', mysql.DATETIME(), nullable=True),
    sa.Column('login_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('customer_id', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='users_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('product_categories',
    sa.Column('category_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('product_id', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='product_categories_ibfk_1'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_categories_ibfk_2'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('countries',
    sa.Column('version', mysql.DATETIME(), nullable=True),
    sa.Column('creation_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=3), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('customers',
    sa.Column('version', mysql.DATETIME(), nullable=True),
    sa.Column('creation_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=2), nullable=False),
    sa.Column('unique_id', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=14), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('iban', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('bank', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('swift', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('city_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name='customers_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('textures',
    sa.Column('version', mysql.DATETIME(), nullable=True),
    sa.Column('creation_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('composition', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('roles_users',
    sa.Column('user_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('role_id', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='roles_users_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='roles_users_ibfk_1'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('sizes',
    sa.Column('version', mysql.DATETIME(), nullable=True),
    sa.Column('creation_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('size', mysql.VARCHAR(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('attributes',
    sa.Column('version', mysql.DATETIME(), nullable=True),
    sa.Column('creation_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('product_sizes',
    sa.Column('size_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('product_id', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_sizes_ibfk_2'),
    sa.ForeignKeyConstraint(['size_id'], ['sizes.id'], name='product_sizes_ibfk_1'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('product_attributes',
    sa.Column('version', mysql.DATETIME(), nullable=True),
    sa.Column('creation_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('value', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('attribute_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('product_id', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], name='product_attributes_ibfk_1'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_attributes_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('categories',
    sa.Column('version', mysql.DATETIME(), nullable=True),
    sa.Column('creation_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('template', mysql.TEXT(), nullable=True),
    sa.Column('parent_id', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('regions',
    sa.Column('version', mysql.DATETIME(), nullable=True),
    sa.Column('creation_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=3), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('country_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name='regions_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regions')
    op.drop_table('categories')
    op.drop_table('product_attributes')
    op.drop_table('product_sizes')
    op.drop_table('attributes')
    op.drop_table('sizes')
    op.drop_table('roles_users')
    op.drop_table('textures')
    op.drop_table('customers')
    op.drop_table('countries')
    op.drop_table('product_categories')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('product_images')
    op.drop_table('cities')
    op.drop_table('products')
    op.drop_table('addresses')
    op.drop_table('product_textures')
    ### end Alembic commands ###

