"""add published flag

Revision ID: 5a0620f00bb
Revises: 2729b656599
Create Date: 2015-01-21 21:10:10.711611

"""

# revision identifiers, used by Alembic.
revision = '5a0620f00bb'
down_revision = '2729b656599'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('published', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'published')
    ### end Alembic commands ###
